# Generated by Django 5.1.2 on 2024-10-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('describtion', models.TextField()),
                ('price', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['brand'],
            },
        ),
    ]
