# Generated by Django 5.1.2 on 2024-10-17 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilephone',
            options={'ordering': ['id', 'brand']},
        ),
    ]
